"""empty message

Revision ID: 637e1437b3b6
Revises: 
Create Date: 2020-11-18 12:42:47.000860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '637e1437b3b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobname', sa.String(length=100), nullable=True),
    sa.Column('requirement', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('prereq', sa.String(length=200), nullable=True),
    sa.Column('skills', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('userpsw', sa.String(length=20), nullable=True),
    sa.Column('exitingskills', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('Job1')
    op.drop_table('Resource1')
    op.drop_table('Users1')
    op.drop_table('Knowledge1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Knowledge1',
    sa.Column('KnowledgeID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Topic', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('Prerequisite', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('Skill', mysql.VARCHAR(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('KnowledgeID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Users1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userpsw', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ExistingSkills', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Resource1',
    sa.Column('ResourceID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('RequiredCourses', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ResourceLink', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('UserID', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ResourceID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Job1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jobname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('requirement', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('resources')
    op.drop_table('knowledges')
    op.drop_table('jobs')
    # ### end Alembic commands ###
